language: go

go:
  - 1.11.x
  - 1.10.x

git:
  depth: 1

notifications:
  email: false

script:
  - go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)